services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh"]
    command: uvicorn core.asgi:fastapi_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    networks:
      - main_network
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env


  celery_worker:
    build:
      context: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    networks:
      - main_network
    depends_on:
      - web
      - postgres
      - rabbitmq
    env_file:
      - .env

  celery_beat:
    build:
      context: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    networks:
      - main_network
    depends_on:
      - web
      - postgres
      - rabbitmq
      - celery_worker
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: k1core_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_network
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: k1core_rabbitmq
    env_file:
      - .env
    networks:
      - main_network
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:

networks:
  main_network:
